@WebhookService.Api_HostAddress = http://localhost:5133

GET {{WebhookService.Api_HostAddress}}/api/v1/health
Accept: application/json

###

GET {{WebhookService.Api_HostAddress}}/api/v1/info
Accept: application/json

###